Update README.md
chowfie/PROBLEM pull request #5
Opened 2022-09-25 18:19 UTC by chowfie

Descripción del problema y link a archivo con configuraciones.

2022-09-27 10:36 UTC, JJ commented
Por favor, sigue la lista de comprobación que hay en el guión.

2022-09-27 10:49 UTC, chowfie commented
[X] ¿Se trata de un problema real del que se tenga conocimiento personal?
Si ya que suelo viajar bastante con mi familia y es un problema que se nos ha presentado casi siempre.

[X] ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?
Si ya que los datos que se van a utilizar, como los tiempos con más afluencia y horarios se almacenarán en la nube.

[X] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?
Sí, ya que la aplicación se encargará de analizar los datos dados y a partir de ello calculará una ruta óptima a seguir.

[X] ¿Se ha incluido la configuración del repositorio y se ha enlazado desde el 'README'?
Sí, el enlace al archivo de configuraciones está al final del README.

2022-09-27 11:00 UTC, JJ requested changes
Lo siento, el problema parece excesivamente complejo y no está bien definido. Os rogaría que considerárais sólo problemas de los que tuviérais conocimiento personal en el sentido que sepáis dónde están los datos, y son fácils de obtener, aparte de saber qué algoritmo aplicar al modelo para obtener la solución al rpoblema.

2022-09-29 07:31 UTC, chowfie commented
[X] ¿Se trata de un problema real del que se tenga conocimiento personal?
Si ya que al ser estudiante es un problema con el que lidio todos los años.

[X] ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?
Si ya que los datos que se van a utilizar se almacenarán en la nube.

[X] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?
Sí, ya que la aplicación se encargará de extraer los datos de los horarios proporcionados y generará horarios sin incompatibilidades.

[X] ¿Se ha incluido la configuración del repositorio y se ha enlazado desde el 'README'?
Sí, el enlace al archivo de configuraciones está arreglado al final del README.

2022-09-29 09:47 UTC, JJ commented
> [X] ¿Se trata de un problema real del que se tenga conocimiento personal? Si ya que al ser estudiante es un problema con el que lidio todos los años.
> 
> [X] ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube? Si ya que los datos que se van a utilizar se almacenarán en la nube.
> 
> [X] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando? Sí, ya que la aplicación se encargará de extraer los datos de los horarios proporcionados y generará horarios sin incompatibilidades.
> 
> [X] ¿Se ha incluido la configuración del repositorio y se ha enlazado desde el 'README'? Sí, el enlace al archivo de configuraciones está arreglado al final del README.

Esto basta con que lo hagas una vez en el cuerpo. Puedes editarlo las veces que quieras.

2022-09-29 09:48 UTC, JJ approved these changes
:+1:

2022-09-29 09:48 UTC, JJ commented on README.md
> +La principal lógica de negocio de este problema es la extracción de datos de los horarios proporcionados por las universidades. Es decir, estos vienen dados normalmente en PDF, por lo que sería neces
Typo: CSV

2022-10-05 15:00 UTC, merged

2022-10-16 07:46 UTC, JJ commented
¿Algún problema para entregar el objetivo 1?

2022-10-16 16:55 UTC, chowfie commented
Ningún problema, lo único es que esta semana me han ocupado más tiempo otras asignaturas y no he tenido la oportunidad de ponerme todo el tiempo que quería con ello. Esta semana me centraré a tope con él. Gracias.