Descripción de personas
chowfie/PROBLEM pull request #8
Opened 2022-10-22 18:41 UTC by chowfie

2022-10-25 16:26 UTC, chowfie commented
HISTORIAS USUARIOS:
* [X] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [X ] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [X] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [X] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

MILESTONES:
* [X] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [X] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [X] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [X] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [X] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [X] ¿Todos los milestones describen correctamente un producto, y no un
   concepto vago, una funcionalidad o una tarea?
* [X] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [X] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [X]  ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [X]  ¿El milestone 0 es mínimo *y* viable?
* [ ]  ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [ ] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

2022-10-27 07:58 UTC, Carlos-SE requested changes
Deberías echarle un ojo al formato de los milestones, pero en cuanto corrijas eso, pinta bien :+1:

2022-10-27 07:58 UTC, Carlos-SE commented on docs/Objetivo1/milestones.md
> +Desarrollaremos un algoritmo que según las asignaturas que indiquen nuestros usuarios, generará posibles horarios sin incompatibilidades entre estas.
Estructura de datos, obtención de dats y algoritmo para horarios no cumplen la condición de ser un `PMV`. Para cumplir este requisito, tienen que ser cosas entregables, ya sea una base de datos, un archivo, etc. 

También, creo que deberías empezar por el M0 para seguir la estructura que dijimos en clase.

A parte de esto, deberías poner las etiquetas [Mx] en los milestones del repositorio (donde tienes sólo dos y aquí hay tres, tienen que ser los mismos)

2022-10-27 10:45 UTC, chowfie commented
Gracias! Les he dado otra vuelta a los milestones y creo que ahora si está mejor especificado el producto que se debe desarrollar en cada uno.

2022-10-27 15:55 UTC, Carlos-SE approved these changes

2022-10-29 17:24 UTC, chowfie commented
Listo para revisión @JJ

2022-10-30 17:36 UTC, JJ requested changes
Tu _verdadera_ lógica de negocio es la extracción de información. Las historias de usuario tienen que estar relacionadas con la misma. Por supuesto que el milestone cero también. Por, favor, repasa lo que es conveniente y necesario en este milestone.

2022-10-30 17:36 UTC, JJ commented on docs/Objetivo1/historias_usuarios.md
> +   Maria Elena quiere que la aplicación le muestre los posibles horarios que podría tener con las asignaturas que le quedaron de primero y las nuevas de      segundo.
"Mostrar" no es un beneficio ni tiene nada que ver con la lógica de negocio.

2022-10-30 17:36 UTC, JJ commented on docs/Objetivo1/historias_usuarios.md
> +   Reyes quiere crear un horario con las posibles asignatruas que podría coger según las restricciones de su horario y los cursos que quiera cursar.
¿Qué diferencia hay con el anterior?

2022-10-30 17:36 UTC, JJ commented on docs/Objetivo1/historias_usuarios.md
> +   Pablo quiere un horario en el que pueda combinar por lo menos 10 asignaturas que no le convalidaron en un año.
¿Cuál es el beneficio? Es decir, ¿qué tendrá que tener ese horario? ¿Podrías especificar qué es lo que va a obtener aquí Pablo?

2022-10-30 17:36 UTC, JJ commented on docs/Objetivo1/milestones.md
> +El objetivo de este milestone será obtener un fichero que contenga una estructura que modelice los horarios de la universidad, incluyendo horas, asignaturas, cursos, duración y grupo.
¿Sólo un fichero? ¿Lo importante es que sea un fichero?

2022-10-30 17:36 UTC, JJ commented on docs/Objetivo1/milestones.md
> +Diseño e implementación de un sistema que nos permita extraer la información sobre los horarios que están disponibles en las páginas web de la universidad y almacenarlos en su estructura de datos cor
Si esta es la lógica de negocio, ¿cómo ayuda el milestone 0 a implementar esta lógica de negocio?

2022-11-02 16:19 UTC, chowfie commented
Listo para revisión @JJ  . He diferenciado dos tipos de usuario, uno que usa la lógica de negocio y necesita la extracción de datos, y otro que necesita la generación de los usuarios sin incompatibilidades.

He revisado las presentaciones y errores comunes y creo que la parte de los milestones está mejor explicada.

2022-11-02 16:29 UTC, JJ approved these changes
:+1:

2022-11-02 16:35 UTC, merged